name: 'Publish Nuget'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: "Deploy NuGet"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "./src/bin/PowerUtils.Security.*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
